name: Build libc++ with msan

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-package:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build
      run: |
        ./build-with-msan.sh
        ./build-deb.sh

    - name: Create Release
      uses: pozetroninc/github-action-get-latest-release@master
      id: create-release
      with:
        owner: dvd0bvb
        repository: ${{ github.repository }}
        excludes: prerelease, draft
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: libc++-with-msan.deb
        asset_name: libc++-with-msan-${{ steps.create-release.outputs.release }}
        tag: ${{ steps.create-release.outputs.release }}
        overwrite: true